### numpy

* fast
* convenient
* consumes less memory

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
a[2]

3

In [4]:
a[-1]

3

In [5]:
a=np.array([5,6,7])

*ndim*

In [6]:
a=np.array([5,6,7])
a.ndim

1

In [7]:
#2dimensional array
a=np.array([[1,2],[3,4],[5,6]])

In [8]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
a=np.array([[1,2],[3,4],[5,6]])
a.ndim

2

*size* returns the no of elements

In [10]:
#size returns the no of elelments
a=np.array([[1,2],[3,4],[5,6]])
a.size


6

In [11]:
a=np.array([5,6,7])
a.size

3

**shape** returns the no of elements

In [12]:
a=np.array([[1,2],[3,4],[5,6]])
a.shape

(3, 2)

In [13]:
a=np.array([5,6,7])
a.shape

(3,)

**dtype** returns the data type of the array

In [14]:
a=np.array([[1,2],[3,4],[5,6]])
a.dtype

dtype('int32')

In [15]:
a=np.array([5,6,7])
a.dtype

dtype('int32')

In [16]:
a=np.array([5,6,7],dtype=float)
a

array([5., 6., 7.])

In [17]:
a.dtype

dtype('float64')

In [18]:
a=np.array([5,6,7],dtype=complex)
a

array([5.+0.j, 6.+0.j, 7.+0.j])

In [19]:
a.dtype

dtype('complex128')

**zeros((rows,columns))** gives the matrix with specified rows and columns

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.zeros(3)

array([0., 0., 0.])

**ones((rows,columns))** gives all ones

In [22]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.ones(3).shape

(3,)

**np.arange()** is same as range()

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(1,5,2)

array([1, 3])

**np.linspace(start,stop,total numbers)** 

linspace gives the *total numbers* including the start and stop

In [26]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [27]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [28]:
 a

array([5.+0.j, 6.+0.j, 7.+0.j])

**reshape(rows,columns)** reshapes the matrix

In [29]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
a.shape

(3, 2)

In [31]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [33]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

**a.ravel()** flattens your function


In [34]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

**a.sum(axis=)** returns the sum

* axis=0 column
* axis=1 row

In [35]:
a.sum()

21

In [36]:
a.sum(axis=1)

array([ 3,  7, 11])

In [37]:
a.sum(axis=0)

array([ 9, 12])

**a.min()** returns minimum

**a.max()** returns maximum

In [38]:
print('minimum is {}'.format(a.min()))
print('maximum is {}'.format(a.max()))

minimum is 1
maximum is 6


In [39]:
a.min(axis=0)
#column wise minimum

array([1, 2])

In [40]:
a.max(axis=1)
#row wise maximum

array([2, 4, 6])

**np.sqrt(a)** returns sqrt of each element

In [41]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [42]:
np.std(a)

1.707825127659933

In [43]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [44]:
b=np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [45]:
a+b

array([[ 6,  8],
       [10, 12]])

In [46]:
a*b
#element wise multiply

array([[ 5, 12],
       [21, 32]])

**a.dot(b)** matrix multiplication

In [47]:
a.dot(b)
#matirx multiply

array([[19, 22],
       [43, 50]])

### slicing and indexing

In [48]:
n=[0,1,2]

In [49]:
n[0:1]

[0]

In [50]:
n[0:2]

[0, 1]

numpy supports similar kind of slicing also supports revers indexing

In [51]:
a=np.array([5,7,9,11])
a

array([ 5,  7,  9, 11])

In [52]:
a[2:]

array([ 9, 11])

In [53]:
a[:-1]

array([5, 7, 9])

In [72]:
a=np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

**a[row,column]** 

indexing starts from zero

In [73]:
a[1,2]

3

In [74]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [75]:
a[1,1]

2

In [76]:
a[1,2]

3

In [77]:
a[:,1]
#all rows and 2nd column

array([7, 2, 3])

In [78]:
#last row
a[-1]

array([9, 3, 2])

In [79]:
#iterating 
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [80]:
for row in a:
    for element in row:
        print(element,end=' ')
    print()

6 7 8 
1 2 3 
9 3 2 


**a.flat**

In [81]:
c=a.flat

In [82]:
for element in a.flat:
    print(element)

6
7
8
1
2
3
9
3
2


In [85]:
print(a.ravel())

[6 7 8 1 2 3 9 3 2]


In [86]:
c=a.flat

In [87]:
print(c)

In [88]:
a=np.arange(6).reshape((3,2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [89]:
b=np.arange(6,12).reshape((3,2))
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

**np.vstack((a,b))** vertical stack

In [90]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

**np.hstack((a,b))** horizontal stcak

In [91]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [94]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

**np.hsplit(array,n)**

splits columnwise i.e alomg column 

In [96]:
np.hsplit(a,3)
#splits column wise

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

**np.vsplit(array,n)**

splits row wise

In [97]:
np.vsplit(a,2)
#spits row wirse

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [99]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**boolean array**

matrix > 4 

checks each element of the matrix ie >4 and returns the boolean value

In [101]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [102]:
a[b]
#returns the true elements only
#extracting the elements that are greater than 4

array([ 5,  6,  7,  8,  9, 10, 11])

In [103]:
#replacing the numbers that are greater than 4 with other numbers
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

**iterating through numpy arrays**

In [106]:
a=np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
#printing all the rows
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [108]:
for row in a:
    for elem in row:
        print(elem)

0
1
2
3
4
5
6
7
8
9
10
11


**a.flatten()**

flattens the array

In [115]:
#instead of using two for loops we can use a.flatten()
for elem in a.flatten():
    print(elem)

0
1
2
3
4
5
6
7
8
9
10
11


**np.nditer(array,order='  ')**

* order='C' this iteartes through each element row wise i.e one row after other
* order='F' this iteartes through each element column wise i.e one column sfter other

In [119]:
for element in np.nditer(a,order='C'):
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11


In [120]:
for element in np.nditer(a,order="F"):
    print(element)

0
4
8
1
5
9
2
6
10
3
7
11
